import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Navigation from "@/app/_components/Layout/nav";
import { getServerSession } from "next-auth";
import { options } from "@/lib/options";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async  function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
   const session=await getServerSession(options)
  return (
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      {session?.user?(<Navigation />):<></>}
      {children}
    </body>
  );
}
